language: node_js

branches:
  only:
  - release

node_js:
  - "7.8"

before_script:
  - npm i -g firebase-tools
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - firebase deploy --token ${FIREBASE_TOKEN} --non-interactive

notifications:
  slack: scvodigital:iS6dmFQV9DBdzjIMGMkKVvED
